export const aggressiveQuotes = [
  'Stand tall because weak moments do not get to lead.',
  'Pressure is welcome because it shows what is solid.',
  'I do not chase comfort because growth is built where excuses fail.',
  'The hard road suits me because easy paths do not make strong people.',
  'I keep my guard high because respect is earned in the hard rounds.',
  'I train my mind because the first battle is always inside.',
  'I do not fold because my standards are stronger than my mood.',
  'Every setback sharpens me because steel is made by heat and impact.',
  'I move with purpose because wasted motion is for people without goals.',
  'I bring discipline because talent without work is just noise.',
  'The fight starts before the bell, and I win it with preparation.',
  'I do not need easy conditions to bring a hard effort.',
  'When the pressure rises, I become more focused.',
  'I respect the challenge, but I do not bow to it.',
  'I carry myself like someone who has already decided not to quit.',
  'Every round teaches me where my edge needs work.',
  'I keep my chin down and my standards high.',
  'My confidence is built from work nobody clapped for.',
  'I do not talk tough when I can train tougher.',
  'The person who outlasts excuses becomes dangerous to doubt.',
  'I enter hard moments with calm eyes and steady hands.',
  'Fear can speak, but it does not get command.',
  'I sharpen my discipline before I test my strength.',
  'A strong stance begins with a stronger mind.',
  'I do not need anger to be intense.',
  'I bring control where others bring noise.',
  'When the path gets rough, I tighten my focus.',
  'I earn respect by doing the work when it is inconvenient.',
  'A tough day is just another place to prove my standard.',
  'I do not wait for confidence because I build it under pressure.',
  'My effort does not negotiate with discomfort.',
  'I stay ready so pressure never catches me soft.',
  'The hard part is not a wall, it is a test.',
  'I do not back up from work that makes me stronger.',
  'Every challenge has to deal with my discipline first.',
  'I walk into pressure like it owes me progress.',
  'My calm is not weakness, it is control.',
  'I do not need loud words when my actions land heavy.',
  'The standard stays high even when the day hits hard.',
  'I train for the moment when quitting sounds reasonable.',
  'My patience is sharp, and my focus is sharper.',
  'I do not fear the grind because it built my backbone.',
  'I bring a steady heart to difficult places.',
  'The work is hard, and that is exactly why it matters.',
  'I do not need to prove everything at once.',
  'I meet resistance with discipline instead of drama.',
  'The harder the round, the cleaner my focus becomes.',
  'I do not crumble when the moment gets heavy.',
  'My strength is quiet until the work asks for it.',
  'I turn pressure into proof.',
  'A strong person keeps moving when comfort starts bargaining.',
  'I am not here to look tough, I am here to be ready.',
  'I respect every challenge enough to prepare for it.',
  'My mindset enters first and leaves last.',
  'I do not need perfect timing to bring full effort.',
  'Hard days are where I collect evidence.',
  'I stay composed because chaos is easier to beat from a clear head.',
  'My discipline has no off switch for bad moods.',
  'I take the hit, learn the lesson, and step forward.',
  'The edge belongs to the person who keeps showing up.',
  'I build strength where excuses used to live.',
  'I do not chase attention because results speak clearly enough.',
  'A tough mind makes a tough moment smaller.',
  'I keep my promises to myself when nobody is watching.',
  'I would rather be tested than protected from growth.',
  'The strongest version of me is built one hard choice at a time.',
  'I do not panic when the pace gets violent.',
  'My focus gets colder when the moment gets hotter.',
  'I move like someone who respects the cost of weakness.',
  'I do not let fatigue write my ending.',
  'My courage is trained, not borrowed.',
  'The obstacle can be big, but my standard is bigger.',
  'I answer pressure with preparation.',
  'I do not quit just because the work got honest.',
  'Every hard mile puts more steel in my stride.',
  'I stay dangerous to doubt by staying loyal to effort.',
  'My mindset does not flinch every time life raises its voice.',
  'I do the hard thing before the hard thing chooses me.',
  'I bring grit without losing control.',
  'The challenge gets my respect, not my surrender.',
  'I keep moving because momentum belongs to the stubborn.',
  'I do not need rage when resolve is stronger.',
  'My discipline is louder than every excuse.',
  'I take the long road if that is where strength is built.',
  'I do not fold under weight because I train under weight.',
  'My standards stand up even when comfort sits down.',
  'I turn hard lessons into sharper instincts.',
  'I fight for the version of me that refuses to be average.',
  'The mirror knows whether I worked, and that is enough.',
  'I keep my feet planted and my purpose clear.',
  'I do not break rhythm for fear.',
  'My strength is built from choices that cost something.',
  'I carry pressure like fuel, not fear.',
  'A hard round cannot scare a prepared mind.',
  'I do not need the path to be kind for me to be relentless.',
  'I stay sharp because life respects readiness.',
  'The work tests me, and I answer without excuses.',
  'I bring backbone to moments that ask for surrender.',
  'I do not step back from a challenge that can build me.',
  'Victory starts with the decision to keep standing.',
];
