export const cheesyPickupQuotes = [
  'Are you a sunrise, because you make my whole day brighter.',
  'Are you a compass, because I keep finding my way back to you.',
  'Are you a spark, because you make every room feel warmer.',
  'Are you a playlist, because you have been stuck in my head all day.',
  'Are you a map, because I keep getting lost in your smile.',
  'Are you coffee, because you make my heart wake up fast.',
  'Are you a shooting star, because I would make a wish and still choose you.',
  'Are you a puzzle, because everything makes more sense when you are near.',
  'Are you a shortcut, because you are the fastest way to my attention.',
  'Are you a headline, because you are the only story I want to read twice.',
  'Are you made of magnets, because I feel pulled toward you.',
  'Are you a candle, because you make the place glow.',
  'Are you a camera, because every moment with you looks better.',
  'Are you a charger, because you bring my energy back.',
  'Are you a cloud, because you make my thoughts drift your way.',
  'Are you a dictionary, because you give meaning to my day.',
  'Are you a garden, because my mood blooms around you.',
  'Are you a melody, because I keep replaying you in my mind.',
  'Are you a rainbow, because you showed up after a dull day.',
  'Are you a recipe, because you have all the right ingredients.',
  'Are you a bookmark, because I want to come back to this moment.',
  'Are you a lighthouse, because you make everything feel easier to find.',
  'Are you a lucky charm, because my day improved when you appeared.',
  'Are you a calendar, because every date looks better with you on it.',
  'Are you a Wi-Fi signal, because I feel a strong connection.',
  'Are you a song lyric, because you fit perfectly in my head.',
  'Are you a warm blanket, because you make everything feel cozy.',
  'Are you a mirror, because I see someone amazing when I look at you.',
  'Are you a cupcake, because you are making this moment sweeter.',
  'Are you a lighthouse beam, because you caught my attention from far away.',
  'Are you a keyboard, because you are just my type.',
  'Are you a library book, because I would check you out twice.',
  'Are you a traffic light, because you made me stop and stare.',
  'Are you a planet, because my whole world is orbiting your smile.',
  'Are you a phone notification, because you made my heart jump.',
  'Are you a campfire, because everyone else faded into the background.',
  'Are you a snow day, because you made everything feel unexpectedly fun.',
  'Are you a postcard, because you make every place look worth visiting.',
  'Are you a magic trick, because I cannot explain how you did that to my mood.',
  'Are you a trophy, because meeting you feels like a win.',
  'Are you a good pen, because I want to write a future with you.',
  'Are you a moonbeam, because you make the night look softer.',
  'Are you a clock, because time slows down when I notice you.',
  'Are you a painting, because I could look at you for a long time.',
  'Are you a picnic, because you make ordinary grass seem romantic.',
  'Are you a password, because you are hard to guess but worth remembering.',
  'Are you a receipt, because I need proof someone this lovely exists.',
  'Are you a snowflake, because there is no one else like you.',
  'Are you a camp song, because you are easy to remember and hard to forget.',
  'Are you a bright idea, because you just lit up my mind.',
  'Are you a good joke, because I want to tell everyone about you.',
  'Are you a stepping stone, because you just made my day better.',
  'Are you a warm cookie, because you make me smile immediately.',
  'Are you a beach day, because you make everything feel lighter.',
  'Are you a paper airplane, because my thoughts keep flying toward you.',
  'Are you a clean page, because I want to start a story with you.',
  'Are you a soft sweater, because you look like comfort in human form.',
  'Are you a high score, because I cannot stop trying to impress you.',
  'Are you a doorbell, because my heart reacts when you show up.',
  'Are you a tiny umbrella, because you made this drink of a day more fun.',
  'Are you a bright marker, because you stand out in every crowd.',
  'Are you a lunch break, because I have been looking forward to you.',
  'Are you a constellation, because you make the whole sky more interesting.',
  'Are you a seatbelt, because my heart needs protection around you.',
  'Are you a soft pillow, because you make me want to stay a while.',
  'Are you a movie trailer, because now I need to see more.',
  'Are you a confetti cannon, because you just made this room more exciting.',
  'Are you a window seat, because you are clearly the best view.',
  'Are you a weather app, because you make my forecast look sunny.',
  'Are you a bakery window, because I stopped walking when I saw you.',
  'Are you a pencil, because you drew my attention perfectly.',
  'Are you a key, because you unlocked my best smile.',
  'Are you a neon sign, because you make everything around you glow.',
  'Are you a lucky penny, because I am glad I found you.',
  'Are you a good chair, because I could settle in beside you.',
  'Are you a trail marker, because you make the path ahead look better.',
  'Are you a warm mug, because you make both hands and hearts happy.',
  'Are you a flower shop, because you just made the air sweeter.',
  'Are you a blue sky, because you made the whole day open up.',
  'Are you a favorite sweater, because you look impossible to let go of.',
  'Are you a tiny bell, because you made something ring in my heart.',
  'Are you a good pun, because you made me grin before I could stop myself.',
  'Are you a perfect parking spot, because finding you feels rare.',
  'Are you a cozy lamp, because you make this corner feel like home.',
  'Are you a paperclip, because you are holding my attention together.',
  'Are you a dance floor, because my confidence showed up when you did.',
  'Are you a sunrise alarm, because you make waking up sound worth it.',
  'Are you a handwritten note, because you feel personal in the best way.',
  'Are you a garden gate, because I want to see what is on the other side.',
  'Are you a smooth road, because you make the whole trip better.',
  'Are you a lemonade stand, because you made today sweeter on sight.',
  'Are you a tiny magnet, because even my shy side is moving toward you.',
  'Are you a cozy weekend, because I would rearrange my plans for you.',
  'Are you a favorite chapter, because I want to read you again.',
  'Are you a good umbrella, because you make rainy days worth sharing.',
  'Are you a campfire story, because I want to sit closer and hear more.',
  'Are you a fresh notebook, because you make me want to begin something new.',
  'Are you a good dessert, because saving room for you was the right call.',
  'Are you a tiny miracle, because my day was ordinary until you arrived.',
  'Are you a smile collector, because you just took mine without trying.',
];
