export const inspirationalQuotes = [
  'Start where you are and move one step forward.',
  'Small progress still changes the direction of your day.',
  'Your effort matters even before results appear.',
  'Keep going when the next step is clear enough.',
  'Courage grows every time you choose to try.',
  'You can build strength from ordinary moments.',
  'A steady pace can still reach a distant goal.',
  'Today is a clean chance to act with purpose.',
  'You are allowed to grow at your own speed.',
  'Focus on the step that is in front of you.',
  'The work you repeat becomes the strength you keep.',
  'Choose the habit that serves the person you are becoming.',
  'A brave beginning is better than a perfect plan.',
  'Your future changes when your next choice changes.',
  'Keep your promise to yourself today.',
  'You do not need certainty to make progress.',
  'Let discipline carry you when motivation is quiet.',
  'Every honest effort teaches you something useful.',
  'You can start again without starting from nothing.',
  'Growth often feels small while it is happening.',
  'Stay patient with the progress you cannot see yet.',
  'The next right step is enough for now.',
  'Confidence follows the actions you repeat.',
  'You are stronger than the excuse that feels easiest.',
  'Make today a vote for the life you want.',
  'One focused action can change the tone of the day.',
  'You can be tired and still be capable.',
  'Let your values lead when the path feels unclear.',
  'The effort you make today gives tomorrow more room.',
  'You are not behind when you are still moving.',
  'Protect your energy for what truly matters.',
  'Progress begins when you stop waiting for perfect conditions.',
  'A calm mind can still make bold choices.',
  'You can learn your way through what you do not know.',
  'Do the small thing well and build from there.',
  'Your consistency is creating evidence for your belief.',
  'The hard part can become the part that shapes you.',
  'Choose progress over pressure today.',
  'You have survived hard days and learned from them.',
  'Let action answer the doubt.',
  'The person you want to be needs one choice from you now.',
  'Your best effort is worth bringing to the moment.',
  'Stay close to the work that makes you proud.',
  'You can be new at something and still belong there.',
  'The door opens more often after you knock.',
  'Your direction matters more than your speed.',
  'Keep building even when the result is quiet.',
  'Hope gets stronger when it has action beside it.',
  'Trust the progress you earn in small pieces.',
  'Begin again with what you know now.',
  'Your next choice can become your turning point.',
  'A little courage today can change the whole week.',
  'Keep showing up for the version of you that is waiting.',
  'You can make progress without making noise.',
  'The strongest roots grow while no one is watching.',
  'Let your effort be louder than your hesitation.',
  'You are capable of learning what this moment requires.',
  'A clear mind begins with one honest decision.',
  'Do not shrink your goal to match a hard day.',
  'You can carry hope and discipline at the same time.',
  'Every step forward gives fear less room.',
  'You become braver by practicing brave choices.',
  'What you finish today becomes strength tomorrow.',
  'A better rhythm starts with one better action.',
  'Your patience is part of the progress.',
  'You can reset the day with your next decision.',
  'Let the lesson matter more than the mistake.',
  'Your focus is a quiet form of power.',
  'Small wins are still proof that change is moving.',
  'You can keep your standards without losing your peace.',
  'The goal is closer every time you refuse to quit.',
  'Your effort is planting more than you can see.',
  'Choose the path that respects your future self.',
  'You can outgrow old limits one choice at a time.',
  'A steady heart can move through heavy days.',
  'Start simple and let momentum do its work.',
  'You are building evidence with every disciplined action.',
  'Let today be useful even if it is not perfect.',
  'Your courage can be quiet and still be real.',
  'The next step is lighter when you stop carrying every step.',
  'You can honor the past without living there.',
  'Progress asks for honesty more than perfection.',
  'A strong future is made from ordinary decisions repeated well.',
  'You can be proud of effort before applause arrives.',
  'Keep your eyes on the work that changes things.',
  'Your growth is still valid when it is unseen.',
  'Discomfort can be a doorway, not a verdict.',
  'You are one good decision away from momentum.',
  'Let your actions teach your doubts what is true.',
  'You can rise without rushing.',
  'The work you avoid is often the work that frees you.',
  'Choose calm focus over loud worry.',
  'Your life changes when your standards become habits.',
  'You can move forward even while you are healing.',
  'The smallest promise kept can rebuild trust in yourself.',
  'Let the future find you prepared.',
  'You do not need a perfect day to make a strong choice.',
  'Keep becoming someone you can rely on.',
  'The first step counts even when it is small.',
  'Your discipline today is kindness to tomorrow.',
];
