export const risquePickupQuotes = [
  'You have a look that makes my thoughts arrive overdressed and leave late.',
  'That smile of yours could make a quiet room feel a little dangerous.',
  'If chemistry were a warning sign, we would already need caution tape.',
  'I should probably behave, but you are not making that easy.',
  'You are making it hard to remember what I was about to say.',
  'There is something about you that makes innocent ideas lose their innocence.',
  'If we stood any closer, the air would need a minute.',
  'Your voice could make a simple conversation feel like trouble.',
  'I came here with good manners, but you are testing every one of them.',
  'You have the kind of confidence that makes my best lines forget how to behave.',
  'That look could turn a polite hello into a very long evening.',
  'You are the reason my calm face is doing extra work.',
  'I was going to play it cool, but you made the room warmer.',
  'If flirting had a speed limit, you would already have me pulled over.',
  'You make eye contact feel like a dare.',
  'I should keep my distance, but my curiosity has terrible manners.',
  'Your smile feels like it knows exactly what it is doing.',
  'You make small talk feel like it needs a soundtrack after dark.',
  'I had a safe thought, and then you walked in.',
  'You are making restraint look like a very advanced skill.',
  'I would offer you a drink, but you already changed the temperature.',
  'If charm were a spark, you would have this place glowing red.',
  'You are the kind of distraction that deserves a warning label.',
  'I am trying to be respectful, but your smile keeps interrupting.',
  'You make silence feel like it is saying too much.',
  'That confidence should come with a slow-motion entrance.',
  'If I looked at you any longer, my poker face would resign.',
  'You have a way of making harmless words sound interesting.',
  'I was behaving perfectly until your smile made other plans.',
  'You make distance feel like a challenge I want to fail.',
  'That laugh could get a person into delightfully questionable plans.',
  'You are trouble, but you seem like the well-dressed kind.',
  'If my thoughts had captions, I would need to edit them around you.',
  'You make the room feel like it knows a secret.',
  'I am not saying you are distracting, but I forgot the rest of my sentence.',
  'You are the reason my confidence just straightened its shirt.',
  'That smile looks like it starts harmless and ends memorable.',
  'You make me want to lean in and make better decisions badly.',
  'If temptation had a friendly face, it would look a lot like yours.',
  'You are making my self-control work overtime.',
  'I was aiming for charming, but you are pushing me toward bold.',
  'Your eyes have a way of making time feel less innocent.',
  'I could behave all night, but I would rather impress you instead.',
  'You make the word maybe sound much more interesting.',
  'That look feels like a conversation I should not start in public.',
  'You have the kind of smile that makes people forget their exit plan.',
  'If confidence were heat, you would have the windows open.',
  'You are the reason this conversation suddenly needs closer attention.',
  'I would call you dangerous, but you make danger sound polite.',
  'You make my best intentions look negotiable.',
  'That outfit is doing excellent work for my imagination.',
  'I was not planning to flirt this hard, but you raised the standard.',
  'You make a simple hello feel like the start of mischief.',
  'If looks could whisper, yours would be saying something bold.',
  'You are the reason my smile has a secret.',
  'I should look away, but my attention is clearly on your side.',
  'You make the air between us feel very busy.',
  'That grin could make a careful person take a chance.',
  'You are making casual conversation feel unfairly exciting.',
  'I would ask what you are doing later, but my tone might give me away.',
  'Your presence is making my patience less patient.',
  'You look like the kind of idea that starts late and ends later.',
  'If charm were a flame, you would have me standing too close.',
  'You make a raised eyebrow feel like a full conversation.',
  'I am trying to stay smooth, but you are bad for my balance.',
  'That smile could talk me into staying longer than planned.',
  'You make confidence look almost unfair.',
  'If the night had a favorite person, it would choose you.',
  'You are the reason my harmless compliment is trying to grow up.',
  'I would say you look nice, but that feels far too mild.',
  'You make me want to behave just enough to be invited closer.',
  'Your energy feels like it knows how to bend the rules.',
  'I was keeping things simple until you became interesting.',
  'You have a way of making the room feel underdressed.',
  'If I asked you to dance, it would not be because of the music.',
  'You are the reason subtlety just left the conversation.',
  'That look could make a confident person double-check themselves.',
  'You make a quiet corner sound like a very good idea.',
  'I am trying to be cool, but you are melting the plan.',
  'Your smile makes restraint feel like paperwork.',
  'You are the kind of distraction I would not complain about.',
  'If sparks could blush, they would around you.',
  'You make a simple glance feel like a plot twist.',
  'I should keep this classy, but your charm keeps moving the line.',
  'You look like a reason to cancel an early morning.',
  'That confidence has excellent timing and terrible mercy.',
  'You make the word close sound like a goal.',
  'I was not prepared for someone to look this tempting and this composed.',
  'You have a smile that makes careful plans loosen their tie.',
  'If this were a movie, this would be the scene where the music changes.',
  'You make every polite compliment feel underpowered.',
  'I am not staring, I am just losing a very private argument with my attention.',
  'You make trouble look cultured.',
  'That look says you know exactly how charming you are.',
  'You are making my good judgment ask for a night off.',
  'If I got any smoother, it would be entirely your fault.',
  'You make curiosity feel a little too warm.',
  'I would keep this innocent, but you walked in looking like a challenge.',
  'You have the kind of charm that makes a person forget the rules.',
  'You make the distance between us feel personally offensive.',
];
