export const romanticPickupQuotes = [
  'I was not looking for a favorite moment, but you walked in and made one.',
  'Your smile feels like the part of the day I want to keep.',
  'Talking to you feels like coming home to a place I have never been.',
  'If peace had a face, I think it would look a lot like you.',
  'I could spend all evening learning the little things that make you happy.',
  'You make ordinary places feel like somewhere worth remembering.',
  'There is a softness in you that makes the world feel less hurried.',
  'Meeting you feels like a story I would like to read slowly.',
  'Your laugh sounds like a reason to stay a little longer.',
  'If I had to choose a view, I would choose the one with you in it.',
  'You make my day feel like it found its favorite sentence.',
  'I like the way time becomes gentler when I am talking to you.',
  'Your presence has a way of making everything feel more honest.',
  'I did not know a smile could feel like a place to rest.',
  'You make the room feel warmer without trying.',
  'I would cross a crowded room just to hear you say hello.',
  'There is something rare in the way you make people feel seen.',
  'You have the kind of heart that makes attention feel easy.',
  'I could listen to your thoughts and forget to check the time.',
  'You make simple moments feel like memories in progress.',
  'If kindness had a favorite voice, it might sound like yours.',
  'I like the version of myself that shows up around you.',
  'You make stillness feel less lonely.',
  'Your smile has the quiet courage of a sunrise.',
  'I would choose a slow walk with you over a loud night anywhere else.',
  'You have a way of making the future feel less far away.',
  'The best part of this place is that you are in it.',
  'I did not plan to remember tonight, but then I met you.',
  'Your laugh makes the world feel like it is being kinder.',
  'I would like to be the reason your day gets softer.',
  'You make every conversation feel like it has somewhere beautiful to go.',
  'If I could keep one feeling from today, it would be the way you smiled.',
  'There is a calm in you that makes my thoughts breathe easier.',
  'You are the kind of person people write songs about quietly.',
  'I think my favorite place might be wherever you are smiling.',
  'You make attention feel like affection before a word is even said.',
  'I would not mind getting lost if the path kept leading to you.',
  'You have a presence that makes ordinary time feel meaningful.',
  'I like the way your kindness enters a room before you do.',
  'You make my heart feel like it remembered something important.',
  'If I had a wish for tonight, it would be one more conversation with you.',
  'You make silence feel comfortable instead of empty.',
  'I would choose your company over any perfect plan.',
  'Your smile makes patience feel worthwhile.',
  'I want to know the stories behind the light in your eyes.',
  'You make a simple hello feel like a beginning.',
  'The world feels a little less noisy when I am near you.',
  'I would like to make your ordinary days feel cared for.',
  'You have the kind of beauty that becomes stronger when you speak.',
  'I think your laugh could turn a hard day around.',
  'You make my attention feel like it finally found a home.',
  'I would save a seat beside me for you in every version of today.',
  'Your kindness feels like a quiet kind of magic.',
  'I like how easily my smile listens to yours.',
  'You make the smallest moments feel worth noticing.',
  'If warmth were a person, it would borrow your smile.',
  'I could get used to the peace that arrives with you.',
  'You make my best thoughts slow down so they can stay awhile.',
  'I did not expect a conversation to feel this much like sunlight.',
  'Your presence makes the room feel more like a promise.',
  'I would like to be someone your heart feels safe around.',
  'You make the future sound less like a plan and more like a hope.',
  'Your eyes make honesty feel easy.',
  'I like the way your smile makes time feel generous.',
  'You are the reason this ordinary moment feels carefully chosen.',
  'I would rather learn your favorite song than impress a crowded room.',
  'You make kindness look effortless and unforgettable.',
  'I think the day saved its best light for you.',
  'Your voice makes even simple words feel worth hearing.',
  'I would like to be part of the calm you deserve.',
  'You make my heart feel less guarded and more curious.',
  'If comfort had a color, it would look like your smile.',
  'I did not know I needed this moment until you became part of it.',
  'You make me want to be present instead of impressive.',
  'Your laugh is the kind of sound people hope to hear again.',
  'I would choose a quiet table with you over a spotlight without you.',
  'You make the distance between strangers disappear gently.',
  'I like how your presence turns attention into care.',
  'You have a way of making hope feel practical.',
  'I would remember your smile even in a room full of bright things.',
  'You make me want to ask better questions and listen longer.',
  'Your kindness makes beauty feel deeper.',
  'I think meeting you improved the shape of my day.',
  'You make the world feel like it still has soft places.',
  'I would like to be someone who adds ease to your life.',
  'Your smile makes my favorite thoughts feel possible.',
  'You have the kind of calm that makes people want to stay.',
  'I could spend a whole evening finding new reasons to admire you.',
  'You make my heart feel politely certain.',
  'I like the way your joy makes space for everyone near it.',
  'You are the sort of person a good day would be proud to include.',
  'I would choose your real story over anyone else\'s perfect image.',
  'Your presence feels like a gentle yes from the universe.',
  'I want to be careful with the chance to know you.',
  'You make affection feel less like a risk and more like a truth.',
  'I would like to make your smile feel as welcome as it makes me feel.',
  'Your heart seems like the kind of place good things grow.',
  'I think a lifetime could be built from moments as kind as this one.',
  'You make me want to stay, listen, and become better at both.',
  'If romance begins with noticing, then I have already begun.',
];
